version: '3'
services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CLIENT_ID: ${CLIENT_ID}
      REDIRECT_URI: ${REDIRECT_URI}
      CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - .:/workspace:cached
    command: air
